#!/usr/bin/env bash
#
# gen-replay-log.sh BIF MAINDAG  > REPLAY-LOG.md
#
# Generates the growable provenance log: every first-parent commit since the
# bifurcation BIF up to MAINDAG (origin/main-dag), grouped by run (one run per
# release back-merge). Identity per commit = its PR (-> duckdb/duckdb) + its -dag
# commit (-> krlmlr/duckdb). Completed runs are overlaid with the derived SHA /
# absorbed status detected from the run-result branches below.
#
# Why PR+`-dag` and not an origin/main SHA: krlmlr's fork `main` is not a faithful
# mirror of duckdb/duckdb main (some PRs, e.g. #20369, are absent), so the -dag
# substrate + the upstream PR number are the authoritative identity.
set -uo pipefail
BIF="$1"; MAINDAG="$2"
CO="https://github.com/krlmlr/duckdb/commit"
PRU="https://github.com/duckdb/duckdb/pull"

# --- completed-run de-merged segments (PR# -> derived sha), edit as runs land ---
# run #1 result branch + its de-merged checkpoint commit; run #2 likewise.
declare -A R1 R2
fill(){ # $1=map name $2=range
  local -n M=$1
  while read -r sha subj; do
    pr=$(echo "$subj" | grep -oE 'pull/[0-9]+|#[0-9]+' | head -1 | grep -oE '[0-9]+')
    [ -n "$pr" ] && M[$pr]=$sha
  done < <(git log --reverse --first-parent --format='%H %s' "$2" 2>/dev/null)
}
fill R1 "00528f79b..0ffd087cddb5"                       # run #1: de-merge #20488 (4 commits)
fill R2 "3710298ae..d0ab64a4c323"                       # run #2: de-merge #20588 (3 + reconcile)

prnum(){ echo "$1" | grep -oE 'pull/[0-9]+|#[0-9]+' | head -1 | grep -oE '[0-9]+'; }
title(){ echo "$1" | sed -E 's@ \(https://redirect[^)]*\)@@; s@ \(#[0-9]+\)$@@'; }
prlink(){ [ -n "$1" ] && printf '[#%s](%s/%s) ' "$1" "$PRU" "$1"; }
MAXRUN=$(git rev-list --count --first-parent --merges "${BIF}..${MAINDAG}" 2>/dev/null)

cat <<EOF
# Replay log — \`main-v1.5-variegata\`

Generated by \`gen-replay-log.sh\`; **regenerate each run** (skill step 5). Oldest
first (\`git log --reverse\`), grouped by **run** (de-merge === run; one run per
release back-merge). Identity = the upstream **PR** (→ \`duckdb/duckdb\`) and the
\`-dag\` commit (→ \`krlmlr/duckdb\`). Completed runs overlay the derived commit and
its role.

Each run re-roots the de-merged-so-far spine onto the next back-merge's second
parent, so a commit replayed by an earlier run can later go **empty (absorbed)**
once the advancing v1.5 base already reflects it.

Roles: **replayed** \`sha\` (cherry-picked that run) · **empty (absorbed)** (base
already has the change) · **pending** (its run hasn't happened yet).
EOF

run=0; started=0
while IFS=$'\t' read -r sha parents subj; do
  np=$(echo "$parents" | wc -w)
  pr=$(prnum "$subj"); t=$(title "$subj")
  if [ "$np" -ge 2 ]; then
    # back-merge = this run's checkpoint
    echo
    echo "- **[checkpoint] Run #$((run+1)) back-merge** $(prlink "$pr")\"$t\" — \`-dag\` [\`${sha:0:9}\`]($CO/$sha)"
    case $((run+1)) in
      1) echo "  - run #1: clean (no reconcile); checkpoint at the segment's last commit, tree == merge tree";;
      2) echo "  - run #2: linearized as reconcile commit [\`d0ab64a4\`]($CO/d0ab64a4c3232b381bbb058cc23cece04d19f0ee), tree \`e337ce86\` == merge tree";
         echo "    - resolution: merge tree as oracle (manual); removed the NOT-elimination rule (#20394) + regenerated churn";;
      *) echo "  - _pending — run #$((run+1))_";;
    esac
    run=$((run+1)); started=0
    continue
  fi
  if [ "$started" -eq 0 ]; then
    echo
    if [ "$((run+1))" -gt "${MAXRUN:-0}" ]; then
      echo "### Tail (no back-merge yet — appended by step 1 'track main'; becomes run #$((run+1))'s segment when the next back-merge lands)"
    else
      echo "### Run #$((run+1)) segment"
    fi
    started=1
  fi
  echo "- $(prlink "$pr")$t"
  echo "  - \`-dag\`: [\`${sha:0:9}\`]($CO/$sha)"
  if [ -n "$pr" ] && [ -n "${R1[$pr]:-}" ]; then echo "  - run #1: replayed [\`${R1[$pr]:0:9}\`]($CO/${R1[$pr]})"; fi
  if [ -n "$pr" ] && [ -n "${R2[$pr]:-}" ]; then echo "  - run #2: replayed [\`${R2[$pr]:0:9}\`]($CO/${R2[$pr]})"; fi
  # absorbed: was de-merged by run #1 but did not survive into run #2's re-rooted spine
  if [ -n "$pr" ] && [ -n "${R1[$pr]:-}" ] && [ -z "${R2[$pr]:-}" ]; then echo "  - run #2: empty (absorbed — change already on the advanced v1.5 base)"; fi
done < <(git log --reverse --first-parent --format='%H%x09%P%x09%s' "${BIF}..${MAINDAG}" 2>/dev/null)
