#!/usr/bin/env bash
#
# gen-replay-log.sh BIF MAINDAG  > REPLAY-LOG.md
#
# Generates the growable provenance log: every first-parent commit since the
# bifurcation BIF up to MAINDAG (origin/main-dag), grouped by run (one run per
# release back-merge). Identity per commit = its PR (-> duckdb/duckdb) + its -dag
# commit (-> krlmlr/duckdb). Every COMPLETED run carries a per-commit SHA link
# (commits link to krlmlr/duckdb), with a role:
#   replayed  - cherry-picked in that run's de-merge segment (new SHA)
#   copied    - above that run's de-merge point; reattached tree-verbatim (new SHA)
#   empty     - went empty that run (change already in that run's base); no SHA
# Back-merges: linearized (the run that de-merged it) / copied (still a merge that
#   run) / gone (de-merged by an earlier run, now below the bifurcation).
#
# Why PR+`-dag` and not an origin/main SHA: krlmlr's fork `main` is not a faithful
# mirror of duckdb/duckdb main (some PRs, e.g. #20369, are absent), so the -dag
# substrate + the upstream PR number are the authoritative identity.
set -uo pipefail
BIF="$1"; MAINDAG="$2"
CO="https://github.com/krlmlr/duckdb/commit"
PRU="https://github.com/duckdb/duckdb/pull"

# PR# -> SHA over a range. Used both for de-merged segments and full run branches.
declare -A R1 R2 R1ALL R2ALL
fill(){ local -n M=$1; local sha subj pr
  while read -r sha subj; do
    pr=$(echo "$subj" | grep -oE 'pull/[0-9]+|#[0-9]+' | head -1 | grep -oE '[0-9]+')
    [ -n "$pr" ] && M[$pr]=$sha
  done < <(git log --reverse --first-parent --format='%H %s' "$2" 2>/dev/null); }

fill R1    "00528f79b..0ffd087cddb5"                    # run #1 de-merged segment (#20488)
fill R2    "3710298ae..d0ab64a4c323"                    # run #2 de-merged segment (#20588)
fill R1ALL "00528f79b..origin/main-v1.5-variegata-01"   # run #1 full result branch
fill R2ALL "00528f79b..origin/main-v1.5-variegata"      # run #2 full result branch

prnum(){ echo "$1" | grep -oE 'pull/[0-9]+|#[0-9]+' | head -1 | grep -oE '[0-9]+'; }
title(){ echo "$1" | sed -E 's@ \(https://redirect[^)]*\)@@; s@ \(#[0-9]+\)$@@'; }
prlink(){ [ -n "$1" ] && printf '[#%s](%s/%s) ' "$1" "$PRU" "$1"; }
link(){ printf '[`%s`](%s/%s)' "${1:0:9}" "$CO" "$1"; }
MAXRUN=$(git rev-list --count --first-parent --merges "${BIF}..${MAINDAG}" 2>/dev/null)

cat <<EOF
# Replay log — \`main-v1.5-variegata\`

Generated by \`gen-replay-log.sh\`; **regenerate each run** (skill step 5). Oldest
first (\`git log --reverse\`), grouped by **run** (de-merge === run; one run per
release back-merge). Identity = the upstream **PR** (→ \`duckdb/duckdb\`) and the
\`-dag\` commit (→ \`krlmlr/duckdb\`). Every **completed run** carries a per-commit
SHA (→ \`krlmlr/duckdb\`) with a role:

- **replayed** \`sha\` — cherry-picked in that run's de-merge segment (new SHA);
- **copied** \`sha\` — above that run's de-merge point; reattached tree-verbatim by
  the graft (new SHA, byte-identical tree);
- **empty (absorbed)** — went empty that run (change already in that run's base);
  no SHA. Once absorbed it stays absorbed, so it is written once as **from run
  #N** and later runs are not repeated.

Each run re-roots the de-merged-so-far spine onto the next back-merge's second
parent, so a commit replayed by an earlier run can later go **empty** once the
advancing v1.5 base already reflects it (cherry-pick onto the base is empty —
confirmed; the v1.5 base reached the same state via other commits, so there is no
single attributable v1.5 PR).
EOF

run=0; started=0
while IFS=$'\t' read -r sha parents subj; do
  np=$(echo "$parents" | wc -w); pr=$(prnum "$subj"); t=$(title "$subj")
  if [ "$np" -ge 2 ]; then
    k=$((run+1))
    echo
    echo "- **[checkpoint] Run #$k back-merge** $(prlink "$pr")\"$t\""
    echo "  - \`-dag\`: $(link "$sha")"
    # run #1 column
    if   [ "$k" -eq 1 ]; then echo "  - run #1: linearized (clean; checkpoint == segment tail, tree == merge tree)"
    elif [ -n "${R1ALL[$pr]:-}" ]; then echo "  - run #1: copied (merge) $(link "${R1ALL[$pr]}")"
    else echo "  - run #1: gone (de-merged earlier)"; fi
    # run #2 column
    if   [ "$k" -eq 2 ]; then echo "  - run #2: linearized → reconcile $(link d0ab64a4c3232b381bbb058cc23cece04d19f0ee) (tree \`e337ce86\` == merge tree); removed NOT-elimination (#20394) + regenerated churn"
    elif [ "$k" -lt 2 ]; then echo "  - run #2: gone (de-merged in run #$k; now below the bifurcation)"
    elif [ -n "${R2ALL[$pr]:-}" ]; then echo "  - run #2: copied (merge) $(link "${R2ALL[$pr]}")"
    else echo "  - run #2: —"; fi
    run=$k; started=0; continue
  fi
  if [ "$started" -eq 0 ]; then
    echo
    if [ "$((run+1))" -gt "${MAXRUN:-0}" ]; then
      echo "### Tail (no back-merge yet — appended by step 1 'track main'; becomes run #$((run+1))'s segment when the next back-merge lands)"
    else echo "### Run #$((run+1)) segment"; fi
    started=1
  fi
  echo "- $(prlink "$pr")$t"
  echo "  - \`-dag\`: $(link "$sha")"
  if [ -z "$pr" ]; then echo "  - (no PR#)"; else
    absorbed=0
    # run #1
    if   [ -n "${R1[$pr]:-}" ];    then echo "  - run #1: replayed $(link "${R1[$pr]}")"
    elif [ -n "${R1ALL[$pr]:-}" ]; then echo "  - run #1: copied $(link "${R1ALL[$pr]}")"
    else echo "  - from run #1: empty (absorbed — base already has the change; stays absorbed)"; absorbed=1; fi
    # run #2 (skip once absorbed: absorption persists for all later runs)
    if [ "$absorbed" -eq 0 ]; then
      if   [ -n "${R2[$pr]:-}" ];    then echo "  - run #2: replayed $(link "${R2[$pr]}")"
      elif [ -n "${R2ALL[$pr]:-}" ]; then echo "  - run #2: copied $(link "${R2ALL[$pr]}")"
      else echo "  - from run #2: empty (absorbed — base already has the change; stays absorbed)"; fi
    fi
  fi
done < <(git log --reverse --first-parent --format='%H%x09%P%x09%s' "${BIF}..${MAINDAG}" 2>/dev/null)
