#!/usr/bin/env bash
#
# reconcile-audit.sh <reconcile-commit> — review the cross-side reconciliation a
# de-merge baked into its checkpoint commit.
#
# The reconcile/checkpoint commit's own diff (vs its parent) is exactly what the
# back-merge changed BEYOND the replayed main-side PRs — measured against the
# release-side replay base, so it excludes everything the release line already
# carried. That diff is the audit surface.
#
# Classification:
#   [gen]    generated/regenerated artifact            -> expected churn, not reviewed
#   [REVIEW] non-generated DELETION or SEMANTIC change -> must be reviewed by the agent
#   [skip]   non-generated pure ADDITION (release-side) -> not reviewed
#
# Policy: review = documentation, not a gate. The agent records a FACTUAL note for
# each [REVIEW] line (what changed + which merge resolved it; for feature-level
# deletions, a short history trace) and proceeds — the merge tree is authoritative.
# Never asserts a rationale the code can't prove (that lives in the PR threads).

set -uo pipefail
R="${1:?reconcile/checkpoint commit required}"

# generated-file allowlist (regenerated by `make generate-files`, never hand-merged)
GEN='src/main/config\.cpp|/settings\.hpp|src/common/settings\.json|src/main/settings/|src_backend_parser_gram\.cpp|grammar/.*\.(y|yh)$|enum_util\.(cpp|hpp)|/serialization/.*\.json|/serialize_.*\.cpp'

echo "reconcile delta of $R (vs ${R}^):"
review=0 gen=0 skip=0
while read -r st f _; do
	[ -z "${st:-}" ] && continue
	if printf '%s' "$f" | grep -qE "$GEN"; then
		echo "  [gen]    $st  $f"; gen=$((gen+1))
	else
		case "$st" in
		D)  echo "  [REVIEW] D   $f   (deletion)";        review=$((review+1));;
		M)  echo "  [REVIEW] M   $f   (semantic change)"; review=$((review+1));;
		A)  echo "  [skip]   A   $f   (release-side addition)"; skip=$((skip+1));;
		*)  echo "  [REVIEW] $st  $f"; review=$((review+1));;
		esac
	fi
done < <(git diff --name-status "${R}^" "$R")

echo "--- $review to review, $gen generated, $skip release-side additions ---"
[ "$review" -gt 0 ] && echo "REVIEW each [REVIEW] line: record a factual note (merge tree is the oracle); deep-dive feature-level deletions; do NOT gate."
exit 0
